- package.json
- src/App.js
- src/redux/reducers/index.js
- src/redux/store.js
**added dependencies**
- react-redux
- redux
- redux-thunk
- styled-components
- prop-types
**wired up redux**
**fixed hook that calls users**
#8 
Must install new dependencies locally
Manually tested 
- checked for console errors
- checked that the app had redux
> Setup redux

- package.json
- src/App.css
- src/App.js
- src/components/Logout.js
- src/components/NavBar.js
- src/index.js
- src/store/actions/auth.js
- src/views/Chat.js
- src/views/HomePage.js
- src/views/Login.js
- src/views/Register.js
Added Login & Registration functionality, and created additional views to be used when implementing the chat. I also fixed several typos and removed componentWillMount and used the constructor instead.
Fixes #15 
Only tested in the browser so far.
> Register login functionality

- src/store/actions/auth.js
- src/views/Login.js
- src/views/Register.js
Added an extra input field in the registration form so a Super Admin could add a motto since that was set as required in the schema. If this ends up not being necessary, it can be removed once the functionality is complete. I also refactored the login to take in an email instead of a name, as discussed.
Fixes #16 
It has only been tested in the browser.
> Minor refactoring for Register & Login pages

- src/components/CheckoutForm.js
- src/components/PlanCard.js
- src/components/TeamMembersAddNewMemberModal.js
- src/store/actions/hotel.js
- src/utils/plans.js
- src/views/Billing.js
- src/views/TeamMembers.js
1) Added plan change restrictions on billing view
2) Added add user restriction on team-members view (@DianaIgnatescu this is a draft and it would be great if you could go in and refactor how you see best for the components/the way you're connecting to the store, I basically just did a first-working version)
3) Removed zip code from card elements (team EU)
4) Added super admin nav into billing view
Fixes #27 
Tested Team-Members and Billing components on live server
> Small billing updates

- src/components/layout/Footer.js
> Footer to the bottom

- src/components/Message.js
- src/components/Messages.js
- src/components/chat/searchMachine.js
- src/views/Chat.js
Made Employee Dash responsive at 800px.
Styled the chat message bubbles so they are separated on each side of chat screen.
Fixes #57 
Tested in browser.
> Responsive employee dash

- src/store/actions/rooms.js
- src/store/reducers/rooms.js
- src/views/CompanySettings.js
Added handling fetching and errors back into the rooms reducer. Tested it with Connor and it works as expected.
Tested in the browser
> Re-introduce fetching and errors in rooms reducer

- src/components/Router.js
- src/components/layout/Footer.js
temporary fix footer
Fixes #25 
> temp footer fix

- src/utils/paths.js
- src/views/CheckInOrOut.js
- src/views/CompanySettings.js
- src/views/EmployeeSettings.js
> Small view bugs and  changed DOMAIN

- src/utils/paths.js
> fix domain

- src/components/layout/navbar/NavBar.js
- src/store/reducers/index.js
Upgraded nav to have number of active and queued tickets
Also added active class to nav
also clears out the redux state on logout
Manually tested
> Upgrading nav to have number of active and queued tickets

- src/components/MessageComposer.js
- src/components/Messages.js
- src/components/chat/TicketView.js
- src/utils/paths.js
Made the scroll only target the component and not the component and window. 
> fixed scrolling but with chat

- package.json
- src/components/GuestCheckInForm.js
- src/store/actions/actionTypes.js
- yarn.lock
The `GuestCheckInForm` now generates QR code together with `passcode` for guest to use for login and redirection to the `Guest Client` chat app.
Dependencies installed - `qrcode.react`
Fixes #69 
Tested in browser on localhost.
> QR code generation

- src/components/GuestCheckInForm.js
Removes name input on checkin for subsequent checkins
Fixes #80
> Added name-clear on checkin

- src/App.css
- src/components/layout/Footer.js
- src/components/layout/navbar/NavBar.js
- src/components/layout/navbar/SignedInLink.js
- src/components/layout/navbar/SignedOutLink.js
Moved the styling for the NavBar to a new branch and made a new PR due to conflicts overriding the master. 
Fixes #101 
Tested in the browser
> Navbar styling fix

- src/components/CompanySettingsRoom.js
- src/components/CompanySettingsRoomsList.js
- src/store/actions/rooms.js
- src/views/CompanySettings.js
1) Changes placeholders to values across company settings page.
2) Adds functionality for adding a list of comma separated rooms in one input.
Fixes #90, #91
Manually with localhost.
> Company settings ux

- src/App.css
- src/components/layout/Footer.js
- src/components/layout/navbar/NavBar.js
- src/components/layout/navbar/SignedInLink.js
- src/components/layout/navbar/SignedOutLink.js
- src/index.css
- src/theme/styledTheme.js
- src/views/Register.js
Added styling to registration view. Removed the placeholders to clean it up and made it responsive. There are a few quirks with it mainly due to the fact that the footer isn't fixed to the bottom of the page but that can be fixed once we're polishing it.
Fixes  #107 
Tested in the browser
> Register styling

- src/components/Router.js
- src/components/layout/navbar/NavBar.js
Was bugs with  receptionist nav. This fixes it
Manually
-  [x] I have run the app using my feature and ensured that no functionality is broken
> Fixed nav bar for specific user types

- src/App.js
- src/views/CompanySettings.js
- src/views/Login.js
- src/views/Register.js
Added styling for the Login view to match the Register page. Also fixed the footer to the bottom of the page. Login view should now be responsive and fit in with the rest of the app.
Fixes #111 
Tested in the browser.
> Login styling

- src/components/Router.js
Redirects to chat when going to a bad link
Manually
> fix a bug with employee login

- src/components/EmployeeSettingsForm.js
- src/components/layout/Footer.js
- src/views/EmployeeSettings.js
- src/views/HomePage.js
- src/views/Register.js
Styled the Account Settings view and refactored the footer slightly to make it appear smaller. I also re-did some of the buttons on the home page which where affected when I removed the button styles from App.css. I also swapped some Links with buttons in order to remove an error in the console.
Fixes #117 #118 
Tested in the browser.
> Account settings styling

- src/components/CompanySettingsRoom.js
- src/components/Router.js
- src/components/TeamMember.js
- src/components/reusable/ConfirmModal.js
Made a reusable Confirm modal
- used on delete staff
- used on update and delete room 
#94 
Manually
> Confirm modal

- src/App.js
- src/components/ChatScreen.js
- src/components/ChatScreenHeader.js
- src/components/Message.js
- src/components/Messages.js
- src/components/chat/ChatsList.js
- src/components/chat/TicketView.js
- src/utils/paths.js
- src/views/Chat.js
Cleaned up layout of chat dash and made entire app scroll at 800px
Manually
> Chat dash touch up

- src/components/layout/navbar/NavBar.js
- src/components/layout/navbar/SignedInLink.js
- looks better at smaller screen widths
- nav closes on link select
Manually
> Nav bug fix

- src/App.css
- src/components/GuestCheckInForm.js
- src/components/GuestCheckOutForm.js
- src/components/TeamMembersList.js
- src/components/reusable/ConfirmModal.js
- src/views/CheckInOrOut.js
- made mobile view
- fixed small width issues
- fixed spinner placement
- cleaned up confirm modal
> check in/out loaders placed

- src/components/CompanySettingsRoom.js
- src/components/CompanySettingsRoomsList.js
- src/utils/paths.js
- src/views/CompanySettings.js
Adds ability for users to upload list of room names via csv
NOTE: Requires styling adjustments
Fixes #156 
Manually
> Room list upload

- src/components/EmployeeSettingsForm.js
- src/components/PlanCheckout.js
- src/components/TeamMembersList.js
- src/components/layout/navbar/SignedInLink.js
- src/utils/paths.js
- src/views/EmployeeSettings.js
1. Adds PT checks on employee settings
2. Removes console errors for fa ClassName on PaymentCheckout
3. Removes temp console error for adding team members
Fixes #53 #135 #138
Manually
> Prop type changes/other fixed

- src/store/actions/rooms.js
- src/utils/paths.js
1) Stops continuous loading when duplicate rooms are added
2) Updates the room list as needed, with new rooms if supplied - decided not to add flash responses on duplicates etc. as if the room list contains the supplied room, all is well for the user.
Fixes #155
> Add duplicate rooms continuous loading

- src/components/TeamMember.js
- src/components/TeamMembersAddNewMemberModal.js
- src/components/TeamMembersList.js
- src/utils/paths.js
- src/views/TeamMembers.js
Moves restrictions modal for too many users to 'Add Team Members' button rather than after the form is filled out for adding a new team member.
Fixes #167 
Manually
> Too many users modal

- src/components/ChatScreen.js
- src/views/HomePage.js
- currently landing page buttons only works when the text is clicked
- this makes it so the link is the same size as the button
- added title case to a few more spots that names are used
Manually
> make all register buttons go to register when clicked anywhere on button

- src/components/CardDetails.js
- src/utils/paths.js
1. Renders either 'Edit' or 'Add' on payment method depending if user is first-time-billing
Fixes #192 
Manually
> Small billing view fix

- src/components/ChatScreen.js
- src/components/Message.js
- src/components/MessageComposer.js
- src/components/chat/TicketView.js
- src/store/actions/chat.js
- src/utils/decodeHtml.js
If translate change is clicked and the latest ticket has not been translated to get the language it does it.
Manually tested
> Get language on translate send

- src/components/GuestCheckInForm.js
- src/components/GuestCheckOutForm.js
- src/store/actions/rooms.js
- src/utils/axiosConfig.js
- src/views/CheckInOrOut.js
Fixes a bug, where `Authorization` header in axios requests is `null`. This was because when `axiosConfig` was declared, there was no token in localStorage.
This will call `localStorage.getItem(...)` on every axios request, so it's sending up to date token
Fixes #191 
> Axios config bug

- src/components/ChatScreen.js
- src/components/Messages.js
Handles scrolling better in the chat screen
#214 
Manually been tested
> Scroll chat

- src/components/ChatScreen.js
- src/components/MessageComposer.js
- src/components/Messages.js
- src/components/layout/Footer.js
- src/theme/styledTheme.js
- src/views/Login.js
Changed shadow for buttons on hover. It should now be lighter & more diffused.
Tested in the browser
> Change button shadow on hover & add transitions where missing

- src/views/PrivacyPage.js
> Fix margin issue on Privacy page

- src/components/CompanySettingsRoomsList.js
Fixes the over flow problem for the button in file input
> fix button over flow on upload
